#pragma once

#define DISPLAY_TIME_INTRO_SCENE 2
#define TRANSITION_TIME 0.5

enum STATE{ IDLE, WALK, ATTACK, DEAD };

enum DIRECTION { NOTDIRECTION,FRONT, BACK, LEFT, RIGHT, };

enum OBJECT_ID { NONE, PLAYER, ENEMY, NPC, };

enum STATE_EFFECT { STATE_EFFECT_NONE, PARALYSIS, BURN, SLOW, POISION };